export const offensiveWords = [
  "abortion", "abuse", "alcohol", "anal", "anus", "arson", "ass", "asshole", "b1tch", "bastard", "beastiality",
  "bitch", "bigot", "blowjob", "bomb", "bong", "boob", "booze", "butt", "butthole", "carbuncle", "child", "clitoris",
  "c0ck", "cocksucker", "condom", "corpse", "crap", "c*nt", "damn", "darn", "date rape", "d1ck", "dildo", "dingleberry",
  "drug", "dyke", "f4g", "felch", "fellatio", "feltch", "fetus", "fist", "flange", "fornicate", "f*ck", "fudge packer",
  "gangbang", "genital", "goddamn", "gook", "gore", "hate", "heroin", "hitler", "homoerotic", "homosexual", "hump",
  "incest", "jackass", "jerk", "jizz", "kill", "kinky", "klan", "l3sbian", "masturbate", "molest", "muff", "murder",
  "nazi", "necrophilia", "needle", "negro", "n*gga", "n*gger", "nipple", "nooky", "opiate", "opium", "orgasm",
  "penetration", "penis", "p*ss", "poop", "porn", "pot", "pregnant", "prostitute", "p*ssy", "q***r", "quickie", "rape",
  "reefer", "scat", "screw", "sex", "sh1t", "slut", "smack", "smut", "snatch", "snuff", "son of a b*tch", "spliff",
  "spunk", "suicide", "taboo", "testicle", "threesome", "titties", "tosser", "tramp", "transsexual", "underage",
  "urinate", "vagina", "vibrator", "virgin", "vomit", "vulva", "wank", "weed", "white power", "wh*re", "wtf", "shit",   "murder",
  "child porn",
  "drugs",
  "kys",
  "rape",
  "vape",
  "kill",
  "terror",
  "cocaine",
  "mef",
  "snus",
  "porn",
  "sex",
  "doggy",
  "69",
  "missionary",
  "nude",
  "violence",
  "gun",
  "weapon",
  "abuse",
  "hate",
  "racist",
  "suicide",
  "bomb",
  "threat",
  "illegal",
  "fraud",
  "phishing",
  "exploit",
  "cheat",
  "fraud",
  "counterfeit",
  "cult",
  "incest",
  "nazi",
  "terror",
  "witchcraft",
  "satanic",
  "abortion",
  "genocide",
  "terrorism",
  "assault",
  "kidnap",
  "extortion",
  "riot",
  "protest",
  "arson",
  "riot",
  "assassinate",
  "hostage",
  "extremist",
  "hijack",
  "assassination",
  "assault",
  "fugitive", "homicide", "abduction", "torture", "suicide",
];

const isUsernameOffensive = () => {
  const lowerCaseUsername = username.toLowerCase();
  return offensiveWords.some(word => lowerCaseUsername.includes(word));
};
